### ISSUE TITLE
Resource state `update`

### ISSUE THREAD

**Issue by seiffert** [nousdefions/ansible-iam-module#2]
I'm unsure whether having a `state=update` is a good idea. I ran into this when I tried to ensure that an already existing user has an access_key. IMO the module should allow idempotent operations on users => `state=present` should perform all operations required to ensure that the passed parameters match the IAM resource

**Comment by seiffert** [comment]
( see https://github.com/Jimdo/ansible-iam-module/commit/b7a55a3e0b137c13f3058980990b326fd724e117 )

**Comment by nousdefions** [comment]
Agreed.

**Comment by nousdefions** [comment]
Merged.
